name: stx_form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 4.0.2

homepage: https://github.com/VolodymyrSydorko/stx_form_bloc
repository: https://github.com/VolodymyrSydorko/stx_form_bloc
documentation: https://github.com/VolodymyrSydorko/stx_form_bloc

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^9.2.1
  intl: ^0.20.3
  rxdart: ^0.28.0
  equatable: ^3.0.0
  uuid: ^4.6.0
  darq: ^2.1.0

dev_dependencies:
  test: ^1.32.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5
  lints: ^6.1.0
